// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcFt5TUlwIbFc93kljNoMGMgyiImcq98',
    appId: '1:168684004174:web:37f666a936d2afa7a7741f',
    messagingSenderId: '168684004174',
    projectId: 'photo-app-3b51f',
    authDomain: 'photo-app-3b51f.firebaseapp.com',
    storageBucket: 'photo-app-3b51f.appspot.com',
    measurementId: 'G-1V53KY2GRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc49JE8-_KrF5smimVQuIcnE7mUnxT20A',
    appId: '1:168684004174:android:e4a24408357609c1a7741f',
    messagingSenderId: '168684004174',
    projectId: 'photo-app-3b51f',
    storageBucket: 'photo-app-3b51f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgM_beV0ZQyiWyjv33RcozU4KAiobULJA',
    appId: '1:168684004174:ios:c590d5625ee5eb7ea7741f',
    messagingSenderId: '168684004174',
    projectId: 'photo-app-3b51f',
    storageBucket: 'photo-app-3b51f.appspot.com',
    iosClientId: '168684004174-fsboa2l4hdsktdm6sfsgrb7fcqhcgc8q.apps.googleusercontent.com',
    iosBundleId: 'page.okto.photoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgM_beV0ZQyiWyjv33RcozU4KAiobULJA',
    appId: '1:168684004174:ios:c590d5625ee5eb7ea7741f',
    messagingSenderId: '168684004174',
    projectId: 'photo-app-3b51f',
    storageBucket: 'photo-app-3b51f.appspot.com',
    iosClientId: '168684004174-fsboa2l4hdsktdm6sfsgrb7fcqhcgc8q.apps.googleusercontent.com',
    iosBundleId: 'page.okto.photoapp',
  );
}
